/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    Milkdown: typeof import('./src/components/Milkdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiConfirm: typeof import('./src/components/UiConfirm.vue')['default']
    UiToast: typeof import('./src/components/UiToast.vue')['default']
  }
}
