name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: '版本级别'
        required: true
        type: choice
        options: [patch, minor, major]

env:
  NODE_VERSION: 20

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 创建 tag / release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install

      # 修复 git commit 身份问题 + 去掉 CRLF 警告
      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global core.autocrlf false

      # 自动 bump 版本 & 同步 manifest.json
      - name: Bump version & sync manifest
        id: version
        run: |
          npm version ${{ inputs.level }}
          CLEAN_VER=$(node -p "require('./package.json').version")
          echo "new_version=$CLEAN_VER" >> $GITHUB_OUTPUT

      # 推送 commit 和 tag 到远程
      - name: Push changes & tags
        run: |
          git push origin HEAD
          git push origin --tags

      - name: Build & pack
        run: |
          npm run build
          npm run pack:zip
          mv dist/dist.zip extension-${{ steps.version.outputs.new_version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          files: extension-${{ steps.version.outputs.new_version }}.zip
          generate_release_notes: true


  # 预留：Chrome Web Store 发布（暂时禁用）
  publish-chrome:
    if: false
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Pack extension
        run: npm run pack:zip

      - name: Rename zip
        run: mv dist/dist.zip extension.zip

      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: publish
          client_id: ${{ secrets.CWS_CLIENT_ID }}
          client_secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CWS_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CWS_EXTENSION_ID }}
          zip_file: extension.zip
