name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: '版本级别'
        required: true
        type: choice
        options: [patch, minor, major]

env:
  NODE_VERSION: 20

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 创建 tag / release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install

      - name: Bump version & sync manifest
        id: version
        run: |
          NEW_VER=$(npm version ${{ inputs.level }})
          echo "new_version=$NEW_VER" >> $GITHUB_OUTPUT
          node scripts/sync-version.js

      - name: Build & pack
        run: |
          npm run build
          npm run pack:zip
          mv dist/dist.zip extension-${{ steps.version.outputs.new_version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          name: Release ${{ steps.version.outputs.new_version }}
          files: extension-${{ steps.version.outputs.new_version }}.zip
          generate_release_notes: true

  publish-chrome:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Pack extension
        run: npm run pack:zip

      - name: Rename zip
        run: mv dist/dist.zip extension.zip

      # 发布到 Chrome 商店
      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'
          client_id: ${{ secrets.CWS_CLIENT_ID }}
          client_secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CWS_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CWS_EXTENSION_ID }}
          zip_file: extension.zip
